// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InventoryItem struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewInventory struct {
	Name string `json:"name"`
}

type NewInventoryItem struct {
	InventoryID string `json:"inventoryID"`
	Name        string `json:"name"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
